//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: config.proto

package com.airship.flutter.config

@kotlin.jvm.JvmSynthetic
inline fun airshipEnv(block: com.airship.flutter.config.AirshipEnvKt.Dsl.() -> kotlin.Unit): com.airship.flutter.config.Config.AirshipEnv =
  com.airship.flutter.config.AirshipEnvKt.Dsl._create(com.airship.flutter.config.Config.AirshipEnv.newBuilder()).apply { block() }._build()
object AirshipEnvKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    private val _builder: com.airship.flutter.config.Config.AirshipEnv.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.airship.flutter.config.Config.AirshipEnv.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.airship.flutter.config.Config.AirshipEnv = _builder.build()

    /**
     * <code>string app_key = 1;</code>
     */
    var appKey: kotlin.String
      @JvmName("getAppKey")
      get() = _builder.appKey
      @JvmName("setAppKey")
      set(value) {
          _builder.appKey = value
      }
    /**
     * <code>string app_key = 1;</code>
     */
    fun clearAppKey() {
      _builder.clearAppKey()
    }

    /**
     * <code>string app_secret = 2;</code>
     */
    var appSecret: kotlin.String
      @JvmName("getAppSecret")
      get() = _builder.appSecret
      @JvmName("setAppSecret")
      set(value) {
          _builder.appSecret = value
      }
    /**
     * <code>string app_secret = 2;</code>
     */
    fun clearAppSecret() {
      _builder.clearAppSecret()
    }

    /**
     * <code>.LogLevel log_level = 3;</code>
     */
    var logLevel: com.airship.flutter.config.Config.LogLevel
      @JvmName("getLogLevel")
      get() = _builder.logLevel
      @JvmName("setLogLevel")
      set(value) {
          _builder.logLevel = value
      }
    /**
     * <code>.LogLevel log_level = 3;</code>
     */
    fun clearLogLevel() {
      _builder.clearLogLevel()
    }
  }
}
@kotlin.jvm.JvmSynthetic
inline fun com.airship.flutter.config.Config.AirshipEnv.copy(block: com.airship.flutter.config.AirshipEnvKt.Dsl.() -> kotlin.Unit): com.airship.flutter.config.Config.AirshipEnv =
  com.airship.flutter.config.AirshipEnvKt.Dsl._create(this.toBuilder()).apply { block() }._build()
